import React, { createContext } from 'react'

export const DataContext = createContext()

function DataContextProvider({children}) {
    const vendors = [
        {  
            id: "vn1",
            name: "Beirut Express (Shenton)",
            ratings: 4.9,
            noOfReviews: "500+",
            listing: "https://images.deliveryhero.io/image/fd-sg/LH/x4us-listing.jpg",
            logo: "https://images.deliveryhero.io/image/fd-sg/LH/x4us-listing.jpg",
            cuisine: ["Mexican", "Salad", "Middle Eastern", "Wraps", "Rice Dishes"],
            dietary: [],
            price: "$$",
            deliveryTime: "20-35 min",
            deliveryFee: 0,
            address: "1 Shenton Wy, #01-06, Singapore 068803",
            coordinates: [1.2792796110333398, 103.85034832420642]
        },
        {  
            id: "vn2",
            name: "Lavi Taco (Pearl's Hill Terrace)",
            ratings: 5,
            noOfReviews: "20",
            listing: "https://images.deliveryhero.io/image/fd-sg/LH/nwvl-listing.jpg",
            logo: "https://images.deliveryhero.io/image/fd-sg/LH/nwvl-listing.jpg",
            cuisine: ["Mexican", "Snacks", "Western"],
            dietary: [],
            price: "$$$",
            deliveryTime: "15-30 min",
            deliveryFee: 0,
            address: "195 Pearl's Hill Terrace, #01-54, Singapore 168976",
            coordinates: [1.284845663647168, 103.84157646478016]
        },
        {  
            id: "vn3",
            name: "Good Luck BBQ 上上签四川小酒馆 (New Bridge)",
            ratings: 4.9,
            noOfReviews: "70",
            listing: "https://images.deliveryhero.io/image/fd-sg/LH/kgqw-listing.jpg",
            logo: "https://images.deliveryhero.io/image/fd-sg/sg-logos/cs4os-logo.jpg",
            cuisine: ["Asian", "Rish Dishes"],
            dietary: [],
            price: "$$$",
            deliveryTime: "55-75 min",
            deliveryFee: 5.19,
            address: "277 New Bridge Road 088751",
            coordinates: [1.2823284738147278, 103.84215781906727]
        },
        {  
            id: "vn4",
            name: "Shake Shack (Neil Road)",
            ratings: 4.9,
            noOfReviews: "5000+",
            listing: "https://images.deliveryhero.io/image/fd-sg/LH/y8pd-listing.jpg",
            logo: "https://images.deliveryhero.io/image/fd-sg/sg-logos/cr2rj-logo.jpg",
            cuisine: ["Burgers", "Fast Food", "American", "Beverages", "Chicken"],
            dietary: [],
            price: "$$",
            deliveryTime: "10-25 min",
            deliveryFee: 0,
            address: "89 Neil Rd, #01-01, Singapore 088849",
            coordinates: [1.27853977255384, 103.84175418201356]
        },
        {  
            id: "vn5",
            name: "Lion City Dim Sum (Lau Pa Sat)",
            ratings: 4.7,
            noOfReviews: "18",
            listing: "https://images.deliveryhero.io/image/fd-sg/LH/vwmj-listing.jpg",
            logo: "https://images.deliveryhero.io/image/fd-sg/sg-logos/cb8yb-logo.jpg",
            cuisine: ["Chinese", "Asian", "Seafood", "Singaporean", "Dim Sum"],
            dietary: [],
            price: "$",
            deliveryTime: "20-35 min",
            deliveryFee: 4.99,
            address: "18 Raffles Quay, Singapore 048582",
            coordinates: [1.2806860248680185, 103.85037219656385]
        }
    ]

    const dishes = [
        {
            id: "vn1-d1",
            vendor_id: "vn1",
            name: "Döner Kebab",
            description: "Tombik bread, lettuce, picked cabbage slaw, tomato, onions, pickles, garlic mayo & herbed yoghurt",
            price: 11.90,
            discount: 0.5,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/55877461.jpg",
            availability: true,
        },
        {
            id: "vn1-d2",
            vendor_id: "vn1",
            name: "4 Pcs Falafel",
            description: "Deep-fried fava beans, chickpea croquettes served with tahina & pickles",
            price: 6.90,
            discount: 0.5,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/55867953.jpg",
            availability: true,
        },
        {
            id: "vn1-d3",
            vendor_id: "vn1",
            name: "Kebab Wrap",
            description: "Flour tortilla, lettuce, pickled cabbage slaw, onions, herbed yoghurt & garlic mayo",
            price: 9.90,
            discount: 0,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/55877460.jpg",
            availability: false,
        },
        {
            id: "vn1-d4",
            vendor_id: "vn1",
            name: "Hummus",
            description: "Chickpeas, tahini, lemon juice & extra virgin olive oil. Served with 1 pc pita bread",
            price: 7.9,
            discount: 0,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/55867878.jpg",
            availability: true,
        },
        {
            id: "vn1-d5",
            vendor_id: "vn1",
            name: "Fattoush Salad",
            description: "Mediterranean salad with sumac seasoning & pita",
            price: 9.90,
            discount: 0.4,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/55867962.jpg",
            availability: true,
        },
        {
            id: "vn1-d6",
            vendor_id: "vn1",
            name: "Kebab Bowl",
            description: "Grilled kebab meat served over rice or salad, topped with fresh veggies and sauces like tzatziki or tahini",
            price: 12.90,
            discount: 0,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/55877463.jpg",
            availability: true,
        },
        {
            id: "vn2-d1",
            vendor_id: "vn2",
            name: "SIGNATURE BIRRIA (LIMITED)",
            description: "Signature slow-cooked oxtail & beef brisket braised in a spicy Birria broth, stuffed between crisp flour tortillas held together by melted cheese. For the ultimate experience, dunk it in the broth or sip it as a soup",
            price: 26.00,
            discount: 0,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/57737069.jpg",
            availability: true,
        },
        {
            id: "vn2-d2",
            vendor_id: "vn2",
            name: "Mala Chicken",
            description: "Chuan Chuan style grilled chicken thigh, Szechuan peppercorn, cumin, red cabbage, raw onion, chipotle mayonnaise, salsa roja, cheese, cilantro, corn",
            price: 18.00,
            discount: 0.5,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/43904834.jpg",
            availability: true,
        },
        {
            id: "vn2-d3",
            vendor_id: "vn2",
            name: "Butter Prawn",
            description: "Cold prawn roll style garlic butter sauce, succulent Argentinian prawns, pomelo salad, mayo, red cabbage, lime, flour tortilla",
            price: 27.00,
            discount: 0.8,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/43904833.jpg",
            availability: true,
        },
        {
            id: "vn2-d4",
            vendor_id: "vn2",
            name: "Loaded Nachos",
            description: "With choice of Pulled-beef brisket or Rendang mushrooms [v], cheese, sour cream, pico de gallo, salsa verde, jalapeno pickles, lime, cilantro",
            price: 20,
            discount: 0.4,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/43904839.jpg",
            availability: true,
        },
        {
            id: "vn2-d5",
            vendor_id: "vn2",
            name: "Signature Rendang Pulled Mushroom",
            description: "Signature pulled-mushroom slow-cooked in a rendang rempah (resembles pulled- brisket), red cabbage, cheese, pico de gallo, salsa verde, cilantro, flour tortilla",
            price: 20.00,
            discount: 0.5,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/43904835.jpg",
            availability: true,
        },
        {
            id: "vn2-d6",
            vendor_id: "vn2",
            name: "Vegetable Stir Fry",
            description: "Vietnamese style stir fry vegetables with potatoes, charred peppers & onions, sweet corn, pico de gallo, cilantro, lime, flour tortilla",
            price: 16.00,
            discount: 0.5,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/43904836.jpg",
            availability: true,
        },
        {
            id: "vn3-d1",
            vendor_id: "vn3",
            name: "CS1. Classic Sichuan Pig Trotter Soup 老妈蹄花汤",
            description: "1 Bowl 1碗",
            price: 15.90,
            discount: 0.7,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/6797448.jpg",
            availability: true,
        },
        {
            id: "vn3-d2",
            vendor_id: "vn3",
            name: "B13. Fried Chicken Feed 脆脆掌中宝",
            description: "Crispy, juicy fried chicken tenders served with a side of tangy dipping sauce.",
            price: 4.90,
            discount: 0,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/37401503.jpg",
            availability: false,
        },
        {
            id: "vn3-d3",
            vendor_id: "vn3",
            name: "CV3. Stir-Fried Beijing Cabbage 油渣包菜",
            description: "Crisp Beijing cabbage stir-fried to perfection with savory seasonings, creating a flavorful and satisfying dish.",
            price: 14.90,
            discount: 0,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/37401478.jpg",
            availability: false,
        },
        {
            id: "vn3-d4",
            vendor_id: "vn3",
            name: "CM1. Homemade Bun With Iberian Black Pork 手工酱肉包",
            description: "3PCs 3粒",
            price: 8.90,
            discount: 0.5,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/37401484.jpg",
            availability: true,
        },
        {
            id: "vn3-d5",
            vendor_id: "vn3",
            name: "CM2. Fried Rice With Egg & Grandma's Pickles 外婆灵魂炒饭",
            description: "1 Plate 1份",
            price: 15.90,
            discount: 0,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/37401483.jpg",
            availability: false,
        },
        {
            id: "vn3-d6",
            vendor_id: "vn3",
            name: "C5. Cold Served Rabbit In Zigong Style 冷吃兔",
            description: "Spicy Sichuan dish featuring tender rabbit meat cooked with chili oil, Sichuan peppercorns, and aromatic spices",
            price: 13.90,
            discount: 0,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/44790937.jpg",
            availability: false,
        },
        {
            id: "vn4-d1",
            vendor_id: "vn4",
            name: "ShackBurger (Single)",
            description: "Cheeseburger (single beef patty) with lettuce, tomato, ShackSauce",
            price: 10.90,
            discount: 0.5,
            image: "https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/AS/chains/tabsquare_sg/c1076b731e4df6aafe1d2f689a892433.jpg",
            availability: true,
        },
        {
            id: "vn4-d2",
            vendor_id: "vn4",
            name: "Cheese Fries",
            description: "Cheese sauce packed separately",
            price: 7.30,
            discount: 0.5,
            image: "https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/AS/chains/tabsquare_sg/360a9c462148e079432e721d93bc8dec.jpg",
            availability: true,
        },
        {
            id: "vn4-d3",
            vendor_id: "vn4",
            name: "Chicken Bites 6 Count - Honey Mustard Sauce",
            description: "Pieces of all-natural chicken breast crisp-fried to order, served with your choice of dipping sauce",
            price: 7.60,
            discount: 0,
            image: "https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/AS/chains/tabsquare_sg/224fc7b65ad082a2ff98c24ab12f73bd.jpg",
            availability: true,
        },
        {
            id: "vn4-d4",
            vendor_id: "vn4",
            name: "SmokeShack (Single)",
            description: "Cheeseburger (single beef patty) with all-natural applewood smoked bacon, chopped cherry pepper, ShackSauce",
            price: 12.90,
            discount: 0,
            image: "https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/AS/chains/tabsquare_sg/204d80a00335bc1f30d1eea4af5aede0.jpg",
            availability: true,
        },
        {
            id: "vn4-d5",
            vendor_id: "vn4",
            name: "White Pepper Beef (Single)",
            description: "Monterey Jack cheeseburger topped with caramelized onions, fresh scallions and Sarawak white pepper sauce.",
            price: 12.30,
            discount: 0.4,
            image: "https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/AS/chains/tabsquare_sg/a10d5e9d45b31a175c253bf404ff2a19.jpg",
            availability: true,
        },
        {
            id: "vn4-d6",
            vendor_id: "vn4",
            name: "White Pepper Fries",
            description: "Topped with Sarawak white pepper sauce and fresh scallions",
            price: 7.10,
            discount: 0.5,
            image: "https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/AS/chains/tabsquare_sg/359ca09abd413176120de12ed274fa3e.jpg",
            availability: true,
        },
        {
            id: "vn5-d1",
            vendor_id: "vn5",
            name: "20. Siew Mai 烧卖",
            description: "Special requests may be accommodated at the restaurant's discretion. Let them know here!",
            price: 3.00,
            discount: 0.3,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/52566601.jpg",
            availability: true,
        },
        {
            id: "vn5-d2",
            vendor_id: "vn5",
            name: "21. Prawn Dumpling 虾饺",
            description: "Special requests may be accommodated at the restaurant's discretion. Let them know here!",
            price: 3.40,
            discount: 0.4,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/52566602.jpg",
            availability: true,
        },
        {
            id: "vn5-d3",
            vendor_id: "vn5",
            name: "34. Century Egg Pork Porridge 皮蛋瘦肉粥",
            description: "Main ingredients, pork & century egg",
            price: 3.60,
            discount: 0.4,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/52566613.jpg",
            availability: true,
        },
        {
            id: "vn5-d4",
            vendor_id: "vn5",
            name: "Xiang Xi Dumpling 香茜饺",
            description: "Handmade xiang xi dumpling main ingredients, coriander, pork & shrimp",
            price: 3.00,
            discount: 0.4,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/52566604.jpg",
            availability: true,
        },
        {
            id: "vn5-d5",
            vendor_id: "vn5",
            name: "3. Char Siew Pau 叉烧包 (2pcs)",
            description: "Mini. 2pcs Handmade mini char siew pau. Main ingredients & pork",
            price: 2.20,
            discount: 0.1,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/52566592.jpg",
            availability: true,
        },
        {
            id: "vn5-d6",
            vendor_id: "vn5",
            name: "31. Chee Cheong Fun-prawn 猪肠粉-虾",
            description: "Steamed & thin savoury rolled up rice noodle sheets with prawn fillings",
            price: 3.40,
            discount: 0.3,
            image: "https://images.deliveryhero.io/image/fd-sg/Products/52566611.jpg",
            availability: true,
        }
    ]

    const supermarkets = [
        {  
            id: "sm1",
            name: "pandamart (CBD)",
            listing: "https://images.deliveryhero.io/image/fd-sg/LH/cl5jl-listing.jpg",
            logo: "https://images.deliveryhero.io/image/fd-sg/LH/cl5jl-listing.jpg",
            deliveryTime: "20-35 min",
            deliveryFee: 0,
            address: "101-109 Telok Ayer St",
            coordinates: [1.2817747393019985, 103.84843155739871]
        }
    ]

    const products = [
        {
            id: "sm1-p1",
            name: "Vegetables rescue box (contains 12 different items)",
            description: "The Rescue Box is an eco-friendly option designed to reduce food waste by making use of vegetables that might not meet aesthetic standards but are still fresh and delicious. It's a budget-friendly way to enjoy nutritious produce while supporting sustainability!",
            price: 20.70,
            discount: 0.51,
            image: "https://res.cloudinary.com/dkgnjflxq/image/upload/v1734016496/pandamart-rescue1_jsknhb.png",
            descImage: "https://res.cloudinary.com/dkgnjflxq/image/upload/v1734017084/pandamart-rescue1-desc_bjehkt.png",
            availability: true,
        },
        {
            id: "sm1-p2",
            name: "Fruits rescue box (contains 12 different items)",
            description: "The Rescue Box is an eco-friendly option designed to reduce food waste by rescuing fruits that might not meet aesthetic standards but are still perfectly fresh and flavorful. It's a budget-friendly way to enjoy nutritious fruit while contributing to a more sustainable future!",
            price: 25.80,
            discount: 0.54,
            image: "https://res.cloudinary.com/dkgnjflxq/image/upload/v1734016493/pandamart-rescue2_eveffe.webp",
            descImage: "https://res.cloudinary.com/dkgnjflxq/image/upload/v1734017084/pandamart-rescue2-desc_tqb9tw.png",
            availability: true,
        },
        {
            id: "sm1-p3",
            name: "Canned food rescue box (contains 12 different items)",
            description: "The Rescue Box is an eco-friendly option designed to reduce food waste by offering canned foods that may have damaged packaging but remain perfectly safe and high-quality. It’s a budget-friendly way to enjoy long-lasting, nutritious meals while supporting sustainability!",
            price: 34.10,
            discount: 0.57,
            image: "https://res.cloudinary.com/dkgnjflxq/image/upload/v1734016494/pandamart-rescue3_czphm6.jpg",
            descImage: "https://res.cloudinary.com/dkgnjflxq/image/upload/v1734017085/pandamart-rescue3-desc_evbq5x.png",
            availability: true,
        },
        {
            id: "sm1-p4",
            name: "Freshstory King Tangerines 600g",
            description: "China tangerine",
            price: 4.90,
            discount: 0.29,
            image: "https://images.deliveryhero.io/image/darkstores/sgp/Benelux_Flowers_Food_Pte_Ltd/14112023/6970601451140.jpg",
            descImage: "",
            availability: true,
        },
        {
            id: "sm1-p5",
            name: "brightfarms Australian Cherries (Large Size) 500g",
            description: "Bright and tangy, these fresh cherries offer a perfect balance of sweetness and tartness, great for desserts or enjoying on their own.",
            price: 19.9,
            discount: 0.20,
            image: "https://images.deliveryhero.io/image/darkstores/sgp/Brightfarms/20240527_Frozen_Chilled/79Y649.jpg",
            descImage: "",
            availability: true,
        },
        {
            id: "sm1-p6",
            name: "brightfarms Australia R2E2 Mango 500-600g",
            description: "Indulge in the sweet splendor of R2E2 mangoes by savoring their succulent, juicy flesh. Enjoy them fresh, sliced for a delectable snack, or elevate your culinary creations with their vibrant flavor in salads, smoothies, or desserts. The peak of mango season is an exquisite moment to delight in this tropical treasure.",
            price: 6.9,
            discount: 0.15,
            image: "https://images.deliveryhero.io/image/darkstores/nv-global-catalog/sg/508a478f-88d5-440c-a578-343c330de330.png",
            descImage: "",
            availability: true,
        }
    ]
  
    return (
    <DataContext.Provider value={{
        vendors, dishes, 
        supermarkets, products
        }}>
        {children}
    </DataContext.Provider>
  )
}

export default DataContextProvider;